palette = "kanagawa_dragon"

format = """
[◖](fg:os_bg)$os$username[◗](fg:os_bg) $directory$git_branch$git_commit$git_status $git_metrics$fill$cmd_duration$battery
╰─$character
"""

#  Usuario
[username]
style_user = "bold bg:os_bg fg:os_fg"
style_root = "bold bg:os_bg fg:red"
format = "[$user]($style)"
disabled = false
show_always = true

#  Git configurationt
[git_branch]
symbol = "󰊢 "
style = "bold purple"

[git_commit]
only_detached = false
style = "bold purple"

[git_status]
format = '([\[$all_status\]]($style))'
style = 'bold'
disabled = false
conflicted = "󰞇 "
ahead = "󰜷 "
behind = "󰜮 "
diverged = "󰹺 "
up_to_date = ""
untracked = "󰋖 "
stashed = "󰏗 "
modified = "󰝤 "
staged = "󰐗 "
renamed = "󰑕 "
deleted = "󰍵 "

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = true
format = '([ $added]($added_style)) ([ $deleted]($deleted_style))'

#  Directorio
[directory]
style = "bold fg:dir_fg"
read_only = " "
read_only_style = "red"

#  Cmd Duration
[cmd_duration]
min_time = 500
format = "[  $duration ]($style)"
style = "bold"

# Python
[python]
symbol = " "
style = "bold green"
format = " [$symbol$version]($style)"

# 󰁹 Batería con símbolos Nerd Font visibles
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[[battery.display]]
threshold = 100
style = "bold purple"

# 󰥔 Hora
[time]
disabled = false
format = "[󰔚 $time]($style) "
time_format = "%H:%M"
style = "bold yellow"

# simbolo del sistema
[os]
disabled = false
style = "bg:os_bg fg:os_fg"

[os.symbols]
Arch = "󰣇 "
Macos = " "

[character]
format = "$symbol"
success_symbol = '[>](fg:bold green)'
error_symbol = '[×](fg:bold red)'

#  Paleta Carbonfox
[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_fg = "#08bdba"

#  Paleta Kanagawa Dragon
[palettes.kanagawa_dragon]
red = "#c4746e"
green = "#8a9a7b"
purple = "#938aa9"
yellow = "#c4b28a"
os_bg = "#a6a69c"
os_fg = "#0d0c0c"
dir_fg = "#7fb4ca"
